apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voting-app
      image: kodekloud/examplevotingapp_worker:v1
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "500m"  # Example CPU limit (500 milliCPU)
          memory: "512Mi"  # Example memory limit (512 Mebibytes)
        requests:
          cpu: "100m"  # Example CPU request (100 milliCPU)
          memory: "256Mi"  # Example memory request (256 Mebibytes)
